AWSTemplateFormatVersion: '2010-09-09'

Parameters:
  Domain:
    Type: String
    Description: The domain name to use for both the User Pool and the Route 53 record (linked to CloudFront).
    Default: auth.simonw-aws.cloud # My example domain
  UserPoolId: # Remove if you are creating your User Pool in the same stack
    Type: String
    Description: ID of the Cognito User Pool that you are creating a custom domain for.
    Default: us-east-2_87lhunrJC # My example User Pool
  CertificateArn:
    Type: String
    Description: The ARN of the Amazon Certificate Manager certificate to be associate with your UserPoolDomain.
    Default: arn:aws:acm:us-east-1:273450712882:certificate/86e843a2-e0d3-496c-93b5-d9762da974f9 # My example certificate
  HostedZoneID:
    Type: String
    Description: The ID of the Route 53 hosted zone associated with your registered domain.
    Default: Z3I7ZCKH5Q5GZX # My hosted zone

Resources:
  UserPoolDomainRoute53Linker:
    Type: AWS::CloudFormation::CustomResource
    Version: 1.0.0
    Properties:
      ServiceToken: arn:aws:lambda:us-east-2:273450712882:function:amazon-cognito-custom-domain-link # Lambda in my AWS account
      HostedZoneID: !Ref HostedZoneID
      Domain: !Ref Domain

  UserPoolDomain:
    Type: AWS::Cognito::UserPoolDomain
    Properties:
      UserPoolId: !Ref UserPoolId # Change this if you are also creating your User Pool in the same Stack or using a Nested Stack
      Domain: !Ref Domain 
      CustomDomainConfig:
        CertificateArn: !Ref CertificateArn