AWSTemplateFormatVersion: 2010-09-09
Transform: AWS::Serverless-2016-10-31

Metadata:
  AWS::ServerlessRepo::Application:
    Name: amazon-cognito-domain-distribution
    Description: An AWS CloudFormation Custom Resource for retrieving the DNS name of the Amazon CloudFront distribution backing your Amazon Cognito User Pool's custom domain
    Author: Simon Woldemichael
    SpdxLicenseId: Apache-2.0
    LicenseUrl: LICENSE
    ReadmeUrl: README.md
    Labels:
      [
        "cognito",
        "cloudformation",
        "custom-resource",
        "route53",
        "user-pool-domain",
      ]
    HomePageUrl: https://github.com/swoldemi/amazon-cognito-domain-distribution
    SemanticVersion: 1.1.0
    SourceCodeUrl: https://github.com/swoldemi/amazon-cognito-domain-distribution

Resources:
  CognitoCustomDomainLinkExecutionRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Statement:
          - Action:
              - sts:AssumeRole
            Effect: Allow
            Principal:
              Service:
                - lambda.amazonaws.com
        Version: "2012-10-17"
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole
      Policies:
        - PolicyDocument:
            Statement:
              - Action:
                  - cognito-idp:DescribeUserPoolDomain
                Effect: Allow
                Resource: "*"
            Version: "2012-10-17"
          PolicyName: CognitoCustomDomainLinkLambdaPolicy

  CognitoCustomDomainLinkFunction:
    Type: AWS::Serverless::Function
    Description: Lambda handler for amazon-cognito-domain-distribution
    Properties:
      FunctionName: amazon-cognito-domain-distribution
      Handler: main
      Runtime: go1.x
      MemorySize: 128
      Role: !GetAtt CognitoCustomDomainLinkExecutionRole.Arn
      Timeout: 900 # Set maximum 15 minute timeout to account for CloudFront Distribution DNS name availability

Outputs:
  LambdaFunctionARN:
    Description: CognitoCustomDomainLink Lambda Function ARN
    Value: !GetAtt CognitoCustomDomainLinkFunction.Arn
